Nemesys/Controllers/HallOfFameController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Nemesys.Models.ViewModels;
using Nemesys.Repositories;

namespace Nemesys.Controllers
{
	public class HallOfFameController : Controller
	{
		private readonly IReportRepository reportRepository;
        private readonly UserManager<IdentityUser> userManager;

        public HallOfFameController(IReportRepository reportRepository,
            UserManager<IdentityUser> userManager)
		{
			this.reportRepository = reportRepository;
            this.userManager = userManager;
        }

		public async Task<IActionResult> Index()
		{
			var currentYear = DateTime.Now.Year;
			var topReporters = await reportRepository.GetTopReportersAsync(currentYear);
			//var Username = (await userManager.FindByIdAsync(topReporters.Username.ToString())).UserName;


            var viewModel = new HallOfFameViewModel
			{
				TopReporters = topReporters.ToList()
			};

			return View(viewModel);
		}
	}
}

Nemesys/Controllers/InvestigatorReportController.cs
using Microsoft.AspNetCore.Mvc;
using Nemesys.Models.ViewModels;
using Nemesys.Repositories;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nemesys.Models.Domain;
using Nemesys.Data;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace Nemesys.Controllers
{

    [Authorize(Roles = "Reporter")]
    public class InvestigatorReportController : Controller
    {
        private readonly ITagRepository tagRepository;
        private readonly IReportRepository reportRepository;

        public InvestigatorReportController(ITagRepository tagRepository, IReportRepository reportRepository)
        {
            this.tagRepository = tagRepository;
            this.reportRepository = reportRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            //get tags from repository
            var tags = await tagRepository.GetAllAsync();

            var model = new AddReportRequest
            {
                Tags = tags.Select(x => new SelectListItem { Text = x.DisplayName, Value = x.Id.ToString() })
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddReportRequest addReportRequest)
        {
            // Get the currently logged-in user's ID
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

        
            //Map view model to domain model
            var report = new Report
            {
                Heading = addReportRequest.Heading,
                PageTitle = addReportRequest.PageTitle,
                Content = addReportRequest.Content,
                Location = addReportRequest.Location,
                Description = addReportRequest.Description,
                FeaturedImageUrl = addReportRequest.FeaturedImageUrl,
                UrlHandle = addReportRequest.UrlHandle,
                PublishedDate = addReportRequest.PublishedDate,
                SpottedDate = addReportRequest.SpottedDate,
                Author = addReportRequest.Author,
                Visible = addReportRequest.Visible,
                UserId = userId,
                StatusId = 1
            };

            //Map tags from selected tags
            var selectedTags = new List<Tag>();
            foreach(var selectedTagId in addReportRequest.SelectedTags)
            {
                var selectedTagIdAsGuid = Guid.Parse(selectedTagId);
                var existingTag = await tagRepository.GetAsync(selectedTagIdAsGuid);

                if (existingTag != null)
                {
                    selectedTags.Add(existingTag);
                }
            }

            //mapping tags back to domain model
            report.Tags = selectedTags;

            await reportRepository.AddAsync(report);

            return RedirectToAction("Add");
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            //call the repository
            var reports = await reportRepository.GetAllAsync();

            return View(reports);
        }

        //for non investigators
        [HttpGet]
        public async Task<IActionResult> MyList()
        {
            // Get the currently logged-in user's ID
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);


            //call the repository
            var reports = await reportRepository.GetAllByUserIdAsync(userId);

            return View(reports);
        }



        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            //retreive result from repository
            var report = await reportRepository.GetAsync(id);
            var tagsDomainModel = await tagRepository.GetAllAsync();

            if(report != null)
            {
                //map the domain model to the view model
                var model = new EditReportRequest
                {
                    Id = report.Id,
                    Heading = report.Heading,
                    PageTitle = report.PageTitle,
                    Content = report.Content,
                    Location = report.Location,
                    Description = report.Description,
                    FeaturedImageUrl = report.FeaturedImageUrl,
                    UrlHandle = report.UrlHandle,
                    PublishedDate = report.PublishedDate,
                    SpottedDate = report.SpottedDate,
                    Author = report.Author,
                    Visible = report.Visible,
                    Tags = tagsDomainModel.Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    }),
                    SelectedTags = report.Tags.Select(x => x.Id.ToString()).ToArray()
                };

                return View(model);
            }
                       

            //pass data to view
            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditReportRequest editReportRequest)
        {
            //map view model back to domain model
            var reportDomainModel = new Report
            {
                Id = editReportRequest.Id,
                Heading = editReportRequest.Heading,
                PageTitle = editReportRequest.PageTitle,
                Content = editReportRequest.Content,
                Location = editReportRequest.Location,
                Description = editReportRequest.Description,
                FeaturedImageUrl = editReportRequest.FeaturedImageUrl,
                UrlHandle = editReportRequest.UrlHandle,
                PublishedDate = editReportRequest.PublishedDate,
                SpottedDate = editReportRequest.SpottedDate,
                Author = editReportRequest.Author,
                Visible = editReportRequest.Visible,
                StatusId = 2
            };

            //map tags to domain model
            var selectedTags = new List<Tag>();
            foreach(var selectedTag in editReportRequest.SelectedTags)
            {
                if (Guid.TryParse(selectedTag,out var tag))
                {
                    var foundTag = await tagRepository.GetAsync(tag);

                    if (foundTag != null)
                    {
                        selectedTags.Add(foundTag);
                    }
                }
            }

            reportDomainModel.Tags = selectedTags;



            //Submit Info to repository for update
            var updatedReport = await reportRepository.UpdateAsync(reportDomainModel);


            if(updatedReport != null)
            {
                return RedirectToAction("Edit");
            }

            return RedirectToAction("Edit");
            //redirect to GET
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditReportRequest editReportRequest)
        {
            //talk to repos to delete report and tags
            var deletedReport = await reportRepository.DeleteAsync(editReportRequest.Id);

            if (deletedReport != null)
            {
                //show success
                return RedirectToAction("List");
            }

            return RedirectToAction("Edit", new { id= editReportRequest.Id});
            //Display response
        }



		//investigation statuses
		[HttpPost]
		public async Task<IActionResult> OpenInvestigation(Guid ReportId, RepDetailsViewModel repDetailsViewModel)
		{
			var report = await reportRepository.GetAsync(ReportId);

			report.StatusId = 2;

			await reportRepository.UpdateAsync(report);

			return RedirectToAction("Index", "Reports",
					new { urlHandle = repDetailsViewModel.UrlHandle });
		}


		[HttpPost]
	    public async Task<IActionResult> CloseInvestigation(Guid ReportId, RepDetailsViewModel repDetailsViewModel)
        {
            var report = await reportRepository.GetAsync(ReportId);

            report.StatusId = 3;

            await reportRepository.UpdateAsync(report);

			return RedirectToAction("Index", "Reports",
					new { urlHandle = repDetailsViewModel.UrlHandle });
		}

		[HttpPost]
        public async Task<IActionResult> NoActionNeeded(Guid ReportId, RepDetailsViewModel repDetailsViewModel)
        {
            var report = await reportRepository.GetAsync(ReportId);

            report.StatusId = 4;

            await reportRepository.UpdateAsync(report);

			return RedirectToAction("Index", "Reports",
					new { urlHandle = repDetailsViewModel.UrlHandle });
		}


	}
}

Nemesys/Controllers/InvestigatorTagsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nemesys.Data;
using Nemesys.Models.Domain;
using Nemesys.Models.ViewModels;
using Nemesys.Repositories;


namespace Nemesys.Controllers
{

    [Authorize(Roles = "Investigator")]
    public class InvestigatorTagsController : Controller
    {
        private readonly ITagRepository tagRepository;

        public InvestigatorTagsController(ITagRepository tagRepository)
        {
            this.tagRepository = tagRepository;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> Add(AddTagRequest addTagRequest)
        {
            if (ModelState.IsValid == false)
            {
                return View();
            } 
            //Mapping AddTagRequest to Tag domain model
            var tag = new Tag
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName
            };

           await tagRepository.AddAsync(tag);

            return RedirectToAction("List");
        }


        [HttpGet]
        [ActionName("List")]
        public async Task<IActionResult> List()
        {
            // use dbContext to read the tags
            var tags = await tagRepository.GetAllAsync();

            return View(tags);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var tag = await tagRepository.GetAsync(id);

            if(tag != null) 
            {
                var editTagRequest = new EditTagRequest
                {
                    Id = tag.Id,
                    Name= tag.Name,
                    DisplayName= tag.DisplayName
                };

                return View(editTagRequest);
            }

            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditTagRequest editTagRequest)
        {
            var tag = new Tag
            {
                Id=editTagRequest.Id,
                Name=editTagRequest.Name,
                DisplayName=editTagRequest.DisplayName
            };

            var updatedTag = await tagRepository.UpdateAsync(tag);

            if(updatedTag != null)
            {
                //Show success notif
            }
            else
            {
                //show error notif
            }

            //Show error notif
            return RedirectToAction("Edit", new { id = editTagRequest.Id });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditTagRequest editTagRequest)
        {
            var deletedTag = await tagRepository.DeleteAsync(editTagRequest.Id);

            if(deletedTag != null)
            {
                //show success notif
                return RedirectToAction("List");
            }


            //Show an Error notif
            return RedirectToAction("Edit", new { id = editTagRequest.Id });
        }
    }
}

Nemesys/Controllers/InvestigatorsUsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Nemesys.Models.ViewModels;
using Nemesys.Repositories;

namespace Nemesys.Controllers
{

    [Authorize(Roles = "Investigator")]
    public class InvestigatorsUsersController : Controller
    {
        private readonly IUserRepository userRepository;

        public InvestigatorsUsersController(IUserRepository userRepository) 
        { 
            this.userRepository = userRepository;
        }

        public async Task<IActionResult> List()
        {
            var users = await userRepository.GetAll();

            var usersViewModel = new UserViewModel();
            usersViewModel.Users = new List<User>();

            foreach (var user in users) 
            {
                usersViewModel.Users.Add(new Models.ViewModels.User
                {
                    Id = Guid.Parse(user.Id),
                    Username = user.UserName,
                    Email = user.Email
                });
            }
            return View(usersViewModel);
        }
    }
}

Nemesys/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nemesys</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Nemesys.styles.css" asp-append-version="true" /> 
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>
 </head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Nemesys</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <!--<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>-->

                        <li class="nav-item mx-5">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HallOfFame" asp-action="Index">Hall Of Fame</a>
                        </li>





                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark"
                                   asp-area=""
                                   asp-controller="InvestigatorReport"
                                   asp-action="Add">
                                    Add Report
                                </a>
                            </li>

                            <!--change functionality-->
                            <li class="nav-item">
                                <a class="nav-link text-dark"
                                   asp-area=""
                                   asp-controller="InvestigatorReport"
                                   asp-action="MyList">
                                    My Reports
                                </a>
                            </li>

                        }




                        <!--hide from normal user-->
                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Investigator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark"
                                   asp-area=""
                                   asp-controller="InvestigatorReport"
                                   asp-action="List">
                                    All Reports
                                </a>
                            </li>


                            <li class="nav-item">
                                <a class="nav-link text-dark"
                                           asp-area=""
                                           asp-controller="InvestigatorTags"
                                           asp-action="Add">
                                            Add Tag
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark"
                                           asp-area=""
                                           asp-controller="InvestigatorTags"
                                           asp-action="List">
                                            Show All Tags
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark"
                                   asp-area=""
                                   asp-controller="InvestigatorsUsers"
                                   asp-action="List">
                                    Show All Users
                                </a>
                            </li>

                            <!--
                            <li class="nav-item">
                                <a class="nav-link text-dark"
                                           asp-area=""
                                           asp-controller="InvestigatorReport"
                                           asp-action="Add">
                                            Add Report
                                </a>
                            </li>
                            -->

                        }

                        

                    </ul>
                    
                    <div class="d-flex align-items-center">

                        @if (signInManager.IsSignedIn(User))
                        {
                            <div class="me-3 text-dark">
                                @User?.Identity?.Name
                                </div>

                            <a class="btn me-3 bg-light text-dark"
                               asp-area=""
                               asp-controller="Account"
                               asp-action="Logout">Logout</a>

                        }
                        else
                        {

                            <a class="btn me-3 bg-light text-dark"
                               asp-area=""
                               asp-controller="Account"
                               asp-action="Login">Login</a>

                            <a class="btn me-3 bg-light text-dark"
                               asp-area=""
                               asp-controller="Account"
                               asp-action="Register">Register</a>

                        }

                    </div>
                 

                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
             &copy; 2024 - Nemesys - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>